language: java
jdk:
  - oraclejdk8
  - openjdk7
  - openjdk6

before_script:
  - export MAVEN_OPTS='-Xmx1g -XX:MaxPermSize=512m'

script: 'mvn install -Pproduction'

notifications:
   email:
      recipients:
      - ehtesham@binary.com
      on_success: never
      on_failure: always