language: java
jdk:
  - oraclejdk8
  - openjdk7

before_script:
  - export MAVEN_OPTS='-Xmx1g -XX:MaxPermSize=512m'

script: './mvnw install -Pproduction'

notifications:
  email:
    recipients:
      - nqliujiangtao@gmail.com
    on_success: never
    on_failure: always
